<?php

function clock_angle_menu(){
    $items['clock_angle'] = array(
          'title' => 'Clock Angle',
          'type' => MENU_NORMAL_ITEM,
          'access callback' => TRUE,
          'page callback' => 'drupal_get_form',
          'page arguments' => array('clock_angle_form'),
    );
    $items['clock_angle_success_page'] = array(
          'title' => 'Success',
          'type' => MENU_CALLBACK,
          'page callback' => 'clock_angle_success',
          'access callback' => TRUE,
    );
    return $items;
}

function clock_angle_form(){
    $form['hour'] = array(
        '#title' => 'Hour',
        '#type' => 'textfield',
        '#description' => t('Enter an hour'),
    );
    $form['minute'] = array(
        '#title' => 'Minute',
        '#type' => 'textfield',
        '#description' => t('Enter a minute'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

function clock_angle_form_submit($form, &$form_state){
    $hour = $form_state['values']['hour'];
    $minute = $form_state['values']['minute'];

    $angle_hour = ((60*$hour)+$minute)/2;
    $angle_minute = (6*$minute);
    $final_angle = abs($angle_hour - $angle_minute);

    $_SESSION['clock_angle_output'] = $final_angle;
    $form_state['redirect'] = 'clock_angle_success_page';
}

function clock_angle_success(){
  $output = $_SESSION['clock_angle_output'];
  return "The distance is $output degrees";
}
