<?php

function ping_pong_menu(){

  $items['ping_pong'] = array(
        'title' => 'Ping Pong Problem',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ping_pong_form'),
        'access callback' => TRUE,
      );
  $items['ping_pong_success_page'] = array(
        'title' => 'Success',
        'type' => MENU_CALLBACK,
        'page callback' => 'ping_pong_success',
        'access callbacl' => TRUE,
      );
      return $items;
}

function ping_pong_form(){
  $form['count_goal'] = array(
      '#title' => 'Count Goal',
      '#type' => 'textfield',
      '#description' => t('Please enter the number you want to count up to'),
  );

  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Go',
  );
  return $form;
}
