<?php

function comment_buddy_comment_insert(){
    drupal_set_message( "Thank you! Comment submitted!");
}

function comment_buddy_comment_update(){
    drupal_set_message("Your comment has been changed.");
}

function comment_buddy_comment_delete(){
    $_GET['destination'] = '<front>';
    drupal_set_message("Comment deleted. Good work eating your words." );
}

function comment_buddy_comment_load(){
    drupal_set_message("Your comments have loaded successfully.");
}
